#!/bin/sh

result=$(swaymsg '[app_id="firefox" title="@gmail.com - Gmail"] focus' | jq .[0].success )
if [ "$result" = "false" ]; then
    echo "Opening Gmail in Firefox..."
    firefox --new-window "https://mail.google.com/mail/u/0/#inbox"
fi